name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t flask_app:latest .

      - name: Push Docker image to GitHub Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker tag flask_app:latest ghcr.io/${{ github.repository_owner }}/flask_app:latest
          docker push ghcr.io/${{ github.repository_owner }}/flask_app:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/flask_app:latest
            docker stop flask_app || true
            docker rm flask_app || true
            docker run -d --name flask_app -p 80:5000 ghcr.io/${{ github.repository_owner }}/flask_app:latest
